name: sdprlayers
channels:
    - conda-forge
    - nvidia
    - pytorch
    - defaults
    - conda-forge
    - anaconda
    - mosek

dependencies:
    - python=3.11
    - pip>=22.3
    # Packages
    - matplotlib>=3.6
    - jupyterlab>=3.5
    - ipynbname=2021.3
    - scipy>=1.9.1
    - mosek
    - cvxopt
    - pandas
    - pyvis
    # Torch
    - pytorch
    - torchvision
    - torchaudio
    - pytorch-cuda=11.8
    #Sparse matrix libraries
    - suitesparse      
    - scikit-sparse 
    # Testing & linting
    - pytest>=7.1
    - pytest-cov=4.0
    - flake8=6.0
    - pip:
        - -r requirements.txt
        - -e .
    
    
